geth \
 --nodiscover \
 --networkid 101010 \
 --rpc \
 --rpcport 8545 \
 --rpcaddr localhost \
 --rpcapi "eth,net,web3" \
 --rpccorsdomain "*" \
 --verbosity 4 \
 --port 40303 \
 --nat none \
 --nodekey=node.key
